Automated g4 rollback of changelist 150859899.
*** Reason for rollback ***

Build breakage of //javatests/com/google/apps/bigtop/data/items/integration:JsUnitSuite__test_lib-j2cl_chrome-linux

zip_content/com/google/apps/bigtop/data/items/integration/GwtAddOnCardListIntegrationTest_GeneratedJ2clTest__xplat_generated_suite.js:5: ERROR - Duplicate module: com.google.apps.bigtop.data.items.integration.GwtAddOnCardListIntegrationTest_GeneratedJ2clTest__xplat_generated_suite
goog.module('com.google.apps.bigtop.data.items.integration.GwtAddOnCardListIntegrationTest_GeneratedJ2clTest__xplat_generated_suite');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

*** Original change description ***

Rollforward APT js source extraction.

This CL is a combined rollforward of the previous 3 CLs that had been rolled back: cl/150715472, cl/150717681, and cl/150706694

Automated g4 rollback of changelist 150751047.

*** Reason for rollback ***

Rollforward.

*** Original change description ***

Automated g4 rollback of changelist 150706694.

*** Reason for rollback ***

breaks bigtop builds

*** Original change description ***

Adds ability for APTs to generate js source in addition to native.js...

***

PiperOrigin-RevId: 150899613