Bump google auto-common to 1.1.2
`auto-common` should be upgraded to fix build since https://github.com/google/j2cl/commit/2bfdbd58f9525d009e8041b4a3e1ec76bda9f0d6. Without upgrade build fails with:
```
junit/generator/java/com/google/j2cl/junit/apt/MoreApt.java:91: error: method toString in class Object cannot be applied to given types;
        .map(input -> extractClassName(AnnotationValues.toString(input)))
                                                       ^
  required: no arguments
  found: AnnotationValue
  reason: actual and formal argument lists differ in length
junit/generator/java/com/google/j2cl/junit/apt/MoreApt.java:92: error: incompatible types: inference variable E has incompatible bounds
        .collect(toImmutableList());
                ^
    equality constraints: String
    lower bounds: Object
  where E is a type-variable:
    E extends Object declared in method <E>toImmutableList()
junit/generator/java/com/google/j2cl/junit/apt/MoreApt.java:106: error: method toString in class Object cannot be applied to given types;
      return Optional.of(extractClassName(AnnotationValues.toString(annotationValue.get())));
                                                          ^
  required: no arguments
  found: AnnotationValue
  reason: actual and formal argument lists differ in length
```

Closes https://github.com/google/j2cl/pull/137

PiperOrigin-RevId: 393850359